[package]
name = "toasty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
futures = {version = "0.3.31", features = ["thread-pool"]}
miniquad = "0.4.7"
notify = "7.0.0"
