[[channels]]
name = "rgba_noise_small"

[channels.config]
vflip = true
filter = "linear"
wrap = "repeat"

[[channels]]
name = "rgba_noise_small"

[channels.config]
vflip = true
filter = "nearest"
wrap = "repeat"
